// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ynxrkmjTXWkbfe3CYf8vKGNlDy_Qlqk',
    appId: '1:438404392237:web:0f0f0db60035817ee39fa4',
    messagingSenderId: '438404392237',
    projectId: 'testcrashlytics-71466',
    authDomain: 'testcrashlytics-71466.firebaseapp.com',
    storageBucket: 'testcrashlytics-71466.appspot.com',
    measurementId: 'G-FLBG9TEL54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-mm9_s8WlHRSzl3wgbPhbg74KOEuOBw',
    appId: '1:438404392237:android:7a2a573a46c47025e39fa4',
    messagingSenderId: '438404392237',
    projectId: 'testcrashlytics-71466',
    storageBucket: 'testcrashlytics-71466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8McgRZ1xbMQJp43xpbI_FT5z0ci_V_iw',
    appId: '1:438404392237:ios:5aaab21762dc06c6e39fa4',
    messagingSenderId: '438404392237',
    projectId: 'testcrashlytics-71466',
    storageBucket: 'testcrashlytics-71466.appspot.com',
    iosBundleId: 'com.example.shorebirdtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8McgRZ1xbMQJp43xpbI_FT5z0ci_V_iw',
    appId: '1:438404392237:ios:86d48e50f2e144c4e39fa4',
    messagingSenderId: '438404392237',
    projectId: 'testcrashlytics-71466',
    storageBucket: 'testcrashlytics-71466.appspot.com',
    iosBundleId: 'com.example.shorebirdtest.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ynxrkmjTXWkbfe3CYf8vKGNlDy_Qlqk',
    appId: '1:438404392237:web:16f52fe366264a8ce39fa4',
    messagingSenderId: '438404392237',
    projectId: 'testcrashlytics-71466',
    authDomain: 'testcrashlytics-71466.firebaseapp.com',
    storageBucket: 'testcrashlytics-71466.appspot.com',
    measurementId: 'G-ZHBQL6XP4D',
  );

}